### ISSUE TITLE
bikeshed repo title and hierarchy

### ISSUE THREAD

**Issue by jrperritt** [gophercloud/utils#1]
@jtopjian What are you thinking for the repo name and layout?

**Comment by jtopjian** [comment]
I thought it might make sense to try to mirror Gophercloud as much as possible. For example:

https://github.com/jtopjian/gophertools/tree/master/openstack

If there's a tool that would cover more than one API, maybe it would go under a package that best describes the topic it's covering or under the API service that does most of the work.

**Comment by jrperritt** [comment]
OK, that sounds fine to me. PR away.
