### ISSUE TITLE
Potential nil reference in GetCloudFromYAML

### ISSUE THREAD

**Issue by outcatcher** [gophercloud/utils#115]
There is potential issue in [GetCloudFromYAML](https://github.com/gophercloud/utils/blob/95fb81d3291f1688ff42530ee22248928463b975/openstack/clientconfig/requests.go#L228)

Inside of `gophercloud` this method is always used with `if cloudName != "" { ...`, but this part can lead to error otherwise:

```go
    var cloudIsInCloudsYaml bool
    if cloud == nil {
        // not an immediate error as it might still be defined in secure.yaml
        cloudIsInCloudsYaml = false
    } else {
        cloudIsInCloudsYaml = true
    }

    publicClouds, err := yamlOpts.LoadPublicCloudsYAML()
    if err != nil {
        return nil, fmt.Errorf("unable to load clouds-public.yaml: %s", err)
    }

    var profileName = defaultIfEmpty(cloud.Profile, cloud.Cloud)
```

There is check for nil-ness of `cloud` first, but it is not utilized at `var profileName = defaultIfEmpty(cloud.Profile, cloud.Cloud)`
Also, in case there is no panic at this point, check for `cloudIsInCloudsYaml` becomes unnecessary afterward.

**Comment by jtopjian** [comment]
@outcatcher Thanks for reporting this. I think https://github.com/gophercloud/utils/pull/116 should resolve it - thoughts?

**Comment by outcatcher** [comment]
@jtopjian seems good :)

**Comment by jtopjian** [comment]
@outcatcher Merged! Thanks again for reporting this. Please let me know if you run into any further issues.
