### ISSUE TITLE
Duplicate imageByName functions

### ISSUE THREAD

**Issue by pierreprinetti** [gophercloud/utils#138]
So, it looks like I've made a mistake [when changing `openstack/compute/v2/images`](https://github.com/gophercloud/utils/pull/135) to use imageservice: the up-to-date function [was already present in `openstack/imageservice/v2/images`](https://github.com/gophercloud/utils/blob/master/openstack/imageservice/v2/images/utils.go).

@jtopjian Do you want me to revert #135?

Alternatively, if non-backwards-compatible changes are OK here in `utils`, then I would remove the entire `openstack/compute/v2/images` package: its new implementation is a copy of the one in `imageservice`, and its old implementation (based on the deprecated compute/images endpoint) was not working for us. WDYT?

**Comment by jtopjian** [comment]
Ah, good catch. 

> Alternatively, if non-backwards-compatible changes are OK here

They are.

> then I would remove the entire openstack/compute/v2/images package

Yes, let's remove this from `utils`. The `gophercloud/gophercloud` [`compute/v2/images`](https://github.com/gophercloud/gophercloud/tree/master/openstack/compute/v2/images) package will stay for posterity, but I'm fine with removing things that are using it.
