### ISSUE TITLE
[Auth] Cannot set TLS skip verify

### ISSUE THREAD

**Issue by Lirt** [gophercloud/utils#160]
Hello,

TLS `InsecureSkipVerify` cannot be set in `clientconfig.ClientOpts`.

I tried to workaround by setting whole HTTP client into clientOpts, but I don't see any effect. I used same code when doing authentication using standard gophercloud methods and it was working.

Here is code that I'm using to set HTTP Client with InsecureSkipVerify.

```go
tlsconfig := &tls.Config{}
tlsconfig.InsecureSkipVerify = true
transport := &http.Transport{TLSClientConfig: tlsconfig}
clientOpts.HTTPClient = &http.Client{
	Transport: transport,
}
```

**Comment by jtopjian** [comment]
The [`Verify`](https://github.com/gophercloud/utils/blob/master/openstack/clientconfig/results.go#L38-L39) option should be handling this.

**Comment by pierreprinetti** [comment]
Closing under the understanding that the issue is solved. Please reopen this issue or open a new one if the proposed solution doesn't work.
