### ISSUE TITLE
Gnocchi measures can contain zero value

### ISSUE THREAD

**Issue by ozerovandrei** [gophercloud/utils#28]
Currently `measures` package doesn't allow us to send zero value in the Gnocchi measure.
But it's a completely normal situation to have zero values in measure for some periods of time.

Gnocchi API doesn't deny zero values:
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L454
https://github.com/gnocchixyz/gnocchi/blob/stable/4.1/gnocchi/rest/api.py#L426

**Comment by jtopjian** [comment]
Fixed in #29
