### ISSUE TITLE
clientconfig: Support for clouds-public.yaml

### ISSUE THREAD

**Issue by simonre** [gophercloud/utils#33]
Openstack supports a clouds-public.yaml file for public information about clouds.
https://docs.openstack.org/python-openstackclient/pike/configuration/index.html

I think it would make sense to incluse it here as well. I'd like to work on it.

**Comment by jtopjian** [comment]
sounds good to me :)

**Comment by haxorof** [comment]
Hi,
I did not notice this issue until today but I actually had some implementation for this locally. I also saw that the current pull request was not correct so I just pushed my changed if you want to have a look at it.

Cheers!

**Comment by haxorof** [comment]
Sure! It was my fault that I did not create an issue and did some local implementation and then time pass too quickly. :smile:

I just committed what I had basically and will let @simonre descide what to do.

**Comment by simonre** [comment]
I'm happy to accept your implementation over mine, yours is better anyway 😄 
I left a comment on your code about what to merge from clouds-public. It's quite hard to find documentation on the difference between clouds-public.yaml and secure.yaml but from looking at the source code it looks like only the AuthInfo struct should be merged here. @jtopjian maybe you can take a look at this at well.

**Comment by jtopjian** [comment]
@haxorof Agreed re opening a PR -- it'll be easier to discuss the implementation that way :)

A few quick notes:

1. I agree with @simonre that the values from the public cloud should be overwriting values if they exist. I'm kind of surprised at this behavior, but that's what the code is doing :smile: However, it does look like more than just the `auth` key are being updated.

2. If possible, we should try not to use `mergo`. This places an outside dependency on `gophercloud/utils` which will cause the topic of vendoring to come up. If we can write some helper functions to help with merging, that would be best. We're already using the YAML package, but that's a pretty common package and we can get away without vendoring that (it's also pinned via gopkg.in).

3. It looks like Python's `os-client-config` is using both the `profile` and `cloud` key to relate a cloud to a public cloud, favoring `profile` and falling back to `cloud`:

https://github.com/openstack/os-client-config/blob/e2a593d917533424c6de39774afb8566d4f81db2/os_client_config/config.py#L466

So we need to account for both.

4. It looks like there's some other extra stuff going on here: https://github.com/openstack/os-client-config/blob/e2a593d917533424c6de39774afb8566d4f81db2/os_client_config/config.py#L477-L495. 

My recommendation would be to start with converting the `_expand_vendor_profile` Python function into Go to match feature parity and then refactoring it into "better Go".

**Comment by simonre** [comment]
> However, it does look like more than just the auth key are being updated.

@jtopjian You're right, I somehow missed the "else" at the bottom

**Comment by haxorof** [comment]
Okay I will open a PR as soon as I correct the things mentioned by you @jtopjian and @simonre

Some comments:

1. My implementation that I did is far from perfect and did not really then look into exact details. 😄 Now I have looked and as you say the `auth` key shall be updated.

2. Point taken and will remove dependency to `mergo`.

3. Yes, I was looking into that also now and `profile` replaces `cloud` etc. One thing that I found is that `os-client-config` is superseded by [openstacksdk](https://github.com/openstack/openstacksdk/tree/master/openstack/config) so then it is one less place to look at. 😄 

4. That extra stuff I also tried to find some specification or similar for but that seems hard. There are a bunch of [json-files](https://github.com/openstack/openstacksdk/tree/master/openstack/config/vendors) available in the repo so how do we do here @jtopjian ? Is this something we shall exclude and put that as a limitation for now or how shall these files be provided?

Cheers!

**Comment by jtopjian** [comment]
All sounds good!

3. This is good news :smile: Let's use `openstacksdk` as the basis of the `clientconfig` implementation from now on.

4. Good point. We definitely don't want to bundle the vendor files here. At the same time, if we assume the user also has `openstacksdk` installed, it'll be difficult to determine where on the system the vendor files are located. Let's defer the `get_profile` support for now, _but_ be mindful that someone will probably want it added in the future, so we shouldn't write code that'll somehow make it hard to do. Maybe just add a comment like:

```go
// TODO: this is where reading vendor files should go
```

**Comment by haxorof** [comment]
@simonre: I opened a PR #50 so not you can close yours.

**Comment by simonre** [comment]
Great, thanks 👍

**Comment by jtopjian** [comment]
Implemented in #51
