### ISSUE TITLE
Travis Support

### ISSUE THREAD

**Issue by jtopjian** [gophercloud/utils#5]
We should integrate Travis testing into this repo.

**Comment by jtopjian** [comment]
@jrperritt Hate to push this one on you, but it'll need an auth token.

**Comment by jrperritt** [comment]
No problem, I'll take care of it

**Comment by jrperritt** [comment]
I've enabled the Travis CI service for this repo, but it isn't yet in a position to run the same travis.yml file as in `gophercloud/gophercloud` (e.g. no `script` directory).

@jtopjian If this bug is for adding the travis.yml file as well, I'm not sure when I'll get to that part.

**Comment by jtopjian** [comment]
@jrperritt Would you be able to commit a basic `.travis.yml` file with the [`secure`](https://github.com/gophercloud/gophercloud/blob/master/.travis.yml#L14) token? I can work on getting actual tests to run after that.

**Comment by jrperritt** [comment]
Maybe? It looks like I added that, but I don't remember what's encrypted in that token, nor how I encrypted it.

**Comment by jrperritt** [comment]
I don't have time to look into it in depth, but after briefly reading some of the Travis CI docs, that token may not be necessary.

**Comment by jtopjian** [comment]
Yep, looks like you're right. The token must be for some non-basic features like releases and such.

**Comment by jtopjian** [comment]
I think we're good to go for now. Thank you!
