### ISSUE TITLE
Files in SITE_CONFIG_DIR can't be loaded when user.Current() isn't implemented

### ISSUE THREAD

**Issue by kkohtaka** [gophercloud/utils#67]
When we call `findAndReadCloudsYAML()` on an environment where `user.Current()` is not implemented, such as "scratch" Docker container, the function returns an error `unable to get current user: ...`.

However, even on such environments, if we have a YAML file in SITE_CONFIG_DIR (/etc/openstack/), the function should load the contents from the file.

**Comment by jtopjian** [comment]
@kkohtaka Setting the `OS_CLIENT_CONFIG_FILE` environment variable to the exact location of the `clouds.yaml` should work around the issue of the non-existent user - can you confirm?

If so, then I'm inclined to just use that as the official solution. My concern with implementing a solution which supports non-existent system users might cause further edge cases to be created. 

Using environment variables to provide the configuration of a Docker container is usually standard practice, too, right?

I might be wrong about this - I'm not a heavy Docker user myself.

**Comment by kkohtaka** [comment]
I confirmed that setting the `OS_CLIENT_CONFIG_FILE` environment variable can be a workaround for this issue.

I agree that the workaround should be the official solution.

Thanks!
