### ISSUE TITLE
Consider replacing satori/go.uuid

### ISSUE THREAD

**Issue by radeksimko** [gophercloud/utils#79]
This library does not seem to be maintained anymore per https://github.com/satori/go.uuid/issues/83 (and mentioned in a few other issues).

It seems that some other folks have switched over to https://github.com/gofrs/uuid

Alternatively HashiCorp maintains this library https://github.com/hashicorp/go-uuid but I have not checked interface compatibility.

Would there be an interest in a PR which replaces the dependency? Is there any preference?

**Comment by jtopjian** [comment]
> Would there be an interest in a PR which replaces the dependency? Is there any preference?

Yes! Thank you. And no preference. If you'd be willing to put the time in, the preference is all yours :)

I'm quite sure this library is only being used here: https://github.com/gophercloud/utils/blob/a5c25e7a53a63b89622852e35d7200c85f7cbe56/acceptance/gnocchi/metric/v1/resources.go

It's only use is to generate a UUID, so I think most alternatives should easily work.
